(executable
 (name fuzz_eio)
 (libraries nats-eio alcobar))

(rule
 (alias runtest)
 (package nats-eio)
 (enabled_if
  (<> %{profile} afl))
 (deps fuzz_eio.exe)
 (action
  (run %{exe:fuzz_eio.exe})))

(rule
 (alias fuzz)
 (package nats-eio)
 (enabled_if
  (= %{profile} afl))
 (deps fuzz_eio.exe)
 (action
  (progn
   (run %{exe:fuzz_eio.exe} --gen-corpus corpus)
   (run afl-fuzz -V 60 -i corpus -o _fuzz -- %{exe:fuzz_eio.exe} @@))))
