(executable
 (name interop_acceptance)
 (modules interop_acceptance)
 (libraries
  nats
  nats-eio
  eio
  eio_main
  tls
  x509
  domain-name
  mirage-crypto-rng.unix
  ptime))

(executable
 (name interop_service_acceptance)
 (modules interop_service_acceptance)
 (libraries
  nats
  nats-eio
  eio
  eio_main
  tls
  x509
  domain-name
  mirage-crypto-rng.unix
  ptime))

(executable
 (name interop_reconnect_acceptance)
 (modules interop_reconnect_acceptance)
 (libraries
  nats
  nats-eio
  eio
  eio_main
  tls
  x509
  domain-name
  mirage-crypto-rng.unix
  ptime))

(executable
 (name interop_jetstream_acceptance)
 (modules interop_jetstream_acceptance)
 (libraries
  nats
  nats-eio
  eio
  eio_main
  tls
  x509
  domain-name
  mirage-crypto-rng.unix
  ptime))

(executable
 (name interop_jetstream_push_acceptance)
 (modules interop_jetstream_push_acceptance)
 (libraries
  nats
  nats-eio
  eio
  eio_main
  tls
  x509
  domain-name
  mirage-crypto-rng.unix
  ptime))

(executable
 (name interop_jetstream_ordered_acceptance)
 (modules interop_jetstream_ordered_acceptance)
 (libraries
  nats
  nats-eio
  eio
  eio_main
  tls
  x509
  domain-name
  mirage-crypto-rng.unix
  ptime))

(executable
 (name interop_jetstream_push_reconnect_acceptance)
 (modules interop_jetstream_push_reconnect_acceptance)
 (libraries
  nats
  nats-eio
  eio
  eio_main
  tls
  x509
  domain-name
  mirage-crypto-rng.unix
  ptime))

(executable
 (name interop_jetstream_ordered_reconnect_acceptance)
 (modules interop_jetstream_ordered_reconnect_acceptance)
 (libraries
  nats
  nats-eio
  eio
  eio_main
  tls
  x509
  domain-name
  mirage-crypto-rng.unix
  ptime))
