(executable
 (name server_acceptance)
 (libraries nats nats-eio eio eio_main))

(executable
 (name server_reconnect)
 (libraries nats nats-eio eio eio_main))

(executable
 (name server_cluster)
 (libraries nats nats-eio eio eio_main))

(executable
 (name server_tls)
 (libraries nats nats-eio eio eio_main tls x509 domain-name
  mirage-crypto-rng.unix ptime))
